#!/usr/bin/env node
// AI OS MCP Server — auto-generated entry point
// This file is generated by ai-os install. Do not edit manually.
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const path = require('path');
const { execFileSync } = require('child_process');

const tsxBin = path.join(path.dirname(new URL(import.meta.url).pathname), 'node_modules', '.bin', 'tsx');
const indexTs = path.join(path.dirname(new URL(import.meta.url).pathname), 'index.ts');

// Try to run via tsx (TypeScript)
try {
  execFileSync(process.execPath, ['--import', 'tsx/esm', indexTs], {
    stdio: 'inherit',
    env: { ...process.env, AI_OS_ROOT: process.env.AI_OS_ROOT ?? process.cwd() },
  });
} catch {
  process.exit(1);
}
